[project]
name = "elegant-wrap-service"
authors = ["ElegantWrap Team"]
description = "Flexible bond wrapping and trading service on Stacks"
telemetry = false
requirements = []
[contracts.bond-wrapper]
path = "contracts/bond-wrapper.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
